name: Publish snap

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  release:
    runs-on: ${{ matrix.runs-on }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        runs-on: [[ubuntu-22.04]]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Complete git history is required to generate the version from git tags.

      - name: Determine system architecture
        run: echo "SYSTEM_ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Download built snap from the build job in check workflow
        uses: actions/download-artifact@v4
        with:
          name: snap_${{ env.SYSTEM_ARCH }}

      - name: Find the downloaded snap file
        run: echo "SNAP_FILE=$(find . -name "*.snap")" >> $GITHUB_ENV

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ env.SNAP_FILE }}
          release: latest/edge
